---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: "devstack"
os:
  name: "ubuntu"
  release: "bionic"
memory: 8192
cpus: 8
numa_nodes: # Total memory for NUMA nodes must be equal to RAM size
  - cpus: 0-3
    memory: 4096
  - cpus: 4-5
    memory: 2048
  - cpus: 6-7
    memory: 2048
