---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

name: "devstack"
os:
  name: "ubuntu"
  release: "focal"
memory: 8192
cpus: 4
numa_nodes: # Total memory for NUMA nodes must be equal to RAM size
  - cpus: 0-1
    memory: 4096
  - cpus: 2-3
    memory: 4096
pmem:
  size: 8G # This value may affect the currentMemory libvirt tag
  slots: 2
  max_size: 16G
  vNVDIMMs:
    - mem_id: mem0
      id: nv0
      share: "on"
      path: /dev/shm
      size: 4G
    - mem_id: mem1
      id: nv1
      share: "on"
      path: /dev/shm
      size: 4G
qat_dev:
  - "3d:00.0"
sriov_dev:
  - "41:02.0"
  - "41:02.1"
  - "41:02.2"
  - "41:02.3"
  - "41:02.4"
  - "41:02.5"
  - "41:02.6"
  - "41:02.7"
